factory:
  - "**/factory*"

dhcpv4:
  - "**/dhcpv4*"

hammer:
  - "**/hammer*"

stats:
  - stats/**/*

generator:
  - generator/**/*

handler:
  - handler/**/*

socketeer:
  - socketeer/**/*

config:
  - config/**/*

cmd:
  - cmd/**/*

repo:
  - ./*
