factory:
  - ./**/factory.go

dhcpv4:
  - ./**/dhcpv4.go

stats:
  - stats/**/*

generator:
  - generator/**/*

handler:
  - handler/**/*

hammer:
  - ./**/hammer.go

socketeer:
  - socketeer/**/*

config:
  - config/**/*

cmd:
  - cmd/**/*

repo:
  - ./*
