name: Run Tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11.x, 1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}        
    - name: setup env
      run: |
        echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
        echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash
    - name: Get dependencies
      run: go get -v -u github.com/ipchama/dhammer
    - name: setup env pt2
      run: |
        cd $GOPATH/src/github.com/ipchama/dhammer
        git checkout $GITHUB_REF
      shell: bash
    - name: Test
      run: go test ./...
